name: test
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  stacked: ^2.3.15
  stacked_generator: ^0.7.14
  stacked_services: ^0.9.3
  stacked_themes: ^0.3.9
  get_it: ^7.2.0
  injectable: ^1.5.3
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.0
flutter:
  uses-material-design: true